<?php

/** @var Appointments[] $appointments_with_file */

use App\Entity\Appointments;

?>

<div class="col-md-4 pl-0 mb-4">
    <input type="search" class="form-control" placeholder="пошук за назвою файла або іменем пацієнта" id="file_search">
</div>

<?php foreach ($appointments_with_file as $appointment) { ?>
<div class="mb-2 file_container" style="line-height:normal;">
    <A href="/admin/appointments/file/?id=<?=$appointment->getId() ?>"><?=basename($appointment->getFile()) ?></A>

    <div class="small">
        <span class="patient_name"><?=$appointment->getName() ?></span> <?=date('d/m/Y', $appointment->getDate()) ?>
    </div>
</div>
<?php } ?>