<div class="mb-4">
    <div class="form-check form-check-inline">
        <input class="form-check-input" type="radio" name="group_by" id="group_by_week" value="week" checked>

        <label class="form-check-label" for="group_by_week">
            тиждень
        </label>
    </div>

    <div class="form-check form-check-inline">
        <input class="form-check-input" type="radio" name="group_by" id="group_by_month" value="month">

        <label class="form-check-label" for="group_by_month">
            місяць
        </label>
    </div>

    <div class="form-check form-check-inline">
        <input class="form-check-input" type="radio" name="group_by" id="group_by_year" value="year">

        <label class="form-check-label" for="group_by_year">
            рік
        </label>
    </div>
</div>

<div id="graph"></div>