<?php

/** @var Articles[] $articles */
/** @var array $reviews */
/** @var array $close_dates */
/** @var string $address */
/** @var string $tel */
/** @var string|null $modal_name */
/** @var Vaccines[] $vaccines */

use App\Entity\Articles;
use App\Entity\Vaccines;

$services=[
    'Консультація педіатрична'                                                              => 700,
    'Консультація неврологічна'                                                             => 900,
    'Комбінована консультація (огляд педіатра та консультація з питань дитячої неврології)' => 1500,
    'Повторна консультація (в межах одного тижня, з приводу первинного звернення)'          => 500,
    'Первинний огляд новонародженого'                                                       => 1000,
    'Консультація з питань грудного вигодовування'                                          => 800,
    'Консультація з дитячого сну'                                                           => 1000,
    'Допологова консультація та підготовка до перших місяців життя дитини'                  => 1200,
    'Виклик лікаря додому (в межах міста)'                                                  => 2000,
];

?>

<script>
    let modal_name='<?=$modal_name ?>';
</script>

<section class="pt-3 pt-lg-5" id="how_to_find">
    <div class="container">
        <div class="row">
            <div class="col-12 row mx-0 justify-content-sm-center align-items-sm-center mb-4 mb-lg-5 font-weight-light" style="font-size:150%;" id="contact_links">
                <div class="col-12 text-center mb-4">
                    <i class="fa fa-map-marker-alt text-muted"></i> м. Чернівці, <span class="text-nowrap"><?=$address ?></span>
                </div>

                <div class="col-12 col-sm-auto text-center col-lg-auto text-nowrap mb-1 mb-sm-0">
                    <A href="tel:<?=$tel ?>" class="text-dark"><i class="fa fa-phone-alt text-muted"></i> <?=preg_replace('/(\d{3})(\d{3})(\d{1})(\d{3})/', '$1 $2 $3 $4', $tel) ?></A>
                </div>

                <div class="col-12 col-sm-auto text-center col-lg-auto text-nowrap mb-1 mb-sm-0">
                    <A href="http://t.me/DitiKviti" class="text-dark"><i class="fab fa-telegram text-muted"></i> DitiKviti</A>
                </div>

                <div class="col-12 col-sm-auto text-center col-lg-auto text-nowrap">
                    <A href="https://www.instagram.com/dr_svitlana/" class="text-dark"><i class="fab fa-instagram text-muted"></i> dr_svitlana</A>
                </div>
            </div>

            <div class="col-md-6 p-0 p-md-2">
                <div class="embed-responsive embed-responsive-4by3 border">
                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d454.2206066851957!2d25.929672882296952!3d48.2955727837393!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x473409506f2a79df%3A0x2c7af818204b8b21!2z0JrQsNCx0ZbQvdC10YIg0LTQuNGC0Y_Rh9C-0LPQviDQu9GW0LrQsNGA0Y8g0JTRltGC0LjQmtCy0ZbRgtC4!5e0!3m2!1suk!2sua!4v1675977279655!5m2!1suk!2sua" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
                </div>
            </div>

            <div class="col-md-6 mt-5 mt-md-0 p-0 p-md-2">
                <div id="photos_carousel" class="carousel slide" data-ride="carousel">
                    <div class="carousel-inner">
                        <div class="carousel-item active">
                            <img class="d-block w-100" src="img/cabinet/1.jpg?date=22-02-2023" alt="">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block w-100" src="img/cabinet/2.jpg?date=22-02-2023" alt="">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block w-100" src="img/cabinet/3.jpg?date=22-02-2023" alt="">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block w-100" src="img/cabinet/4.jpg?date=22-02-2023" alt="">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block w-100" src="img/cabinet/5.jpg?date=22-02-2023" alt="">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block w-100" src="img/cabinet/6.jpg?date=22-02-2023" alt="">
                        </div>
                    </div>

                    <a class="carousel-control-prev" href="#photos_carousel" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">&longrightarrow;</span>
                    </a>
                    <a class="carousel-control-next" href="#photos_carousel" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">&longleftarrow;</span>
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="pt-5" id="reviews">
    <div class="container">
        <h2 class="text-center text-uppercase mb-3 w-100 text-muted font-weight-light"><i class="fas fa-comments"></i> Відгуки</h2>

        <div class="row">
            <?php foreach ($reviews as $name => $review) { ?>
                <div class="col-lg-6 pt-2 pb-3">
                    <blockquote class="alert alert-secondary position-relative px-0 pt-2 pb-0 h-100">
                        <i class="fa fa-quote-right fa-lg text-secondary position-absolute" style="left:0.7rem; top:0.7rem;"></i>

                        <p class="mb-0 pl-5 pr-3 pr-sm-2">
                            <?=$review ?>
                        </p>

                        <footer class="blockquote-footer mt-2 text-center">
                            <?=$name ?> у <cite>відгуках Google</cite>

                            <div class="text-warning small">
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                            </div>
                        </footer>
                    </blockquote>
                </div>
            <?php } ?>

            <div class="col-12 text-center mt-2">
                <A href="/review" class="btn btn-success"><i class="fa fa-pencil-alt mr-1"></i> Залиште свій відгук</A>
            </div>
        </div>
    </div>
</section>

<section class="pt-5" id="articles">
    <div class="container">
        <h2 class="text-center text-uppercase mb-0 w-100 font-weight-light text-muted"><i class="fas fa-notes-medical"></i> Статті</h2>

        <div class="col-md-6 mx-auto px-0 mt-4">
            <input type="search" class="form-control form-control-lg w-100 mx-auto mb-4" placeholder="Швидкий пошук статей" name="quick_search">
        </div>

        <div class="row articles">
            <?php foreach ($articles as $article) { ?>
            <div class="col-sm-6 col-lg-4 mb-4 px-2 article_container">
                <div class="article overflow-hidden mx-auto mb-2 border position-relative" data-article-id="<?=$article->getId() ?>">
                    <div class="article_image" style="background-image:url('img/articles/<?=$article->getId() ?>.jpg');"></div>

                    <div class="article_header position-absolute w-100 text-white text-center text-truncate px-2 py-1 lead" style="bottom:0; left:0; background:rgba(0, 0, 0, 0.45);">
                        <?=$article->getTitle() ?>
                    </div>

                    <?php if ($article->isVideo()) { ?>
                    <div class="position-absolute mr-2 mt-1" style="top:0; right:0;">
                        <div class="badge badge-info badge-pill shadow">
                            відео
                            <i class="fa fa-play-circle"></i>
                        </div>
                    </div>
                    <?php } ?>
                </div>
            </div>
            <?php } ?>
        </div>

        <div class="alert alert-danger text-center col-md-9 mx-auto" style="display:none;" id="articles_not_found">
            За вашим запитом нічого не знайдено
        </div>
    </div>
</section>

<div class="modal fade" id="article_modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header border-bottom-0 pb-0">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            <div class="modal-body pt-1">
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col">
                            <h2 class="text-secondary text-uppercase mb-4 text-center font-weight-light" style="text-wrap:balance;"></h2>

                            <div class="text-center">
                                <IMG class="img-fluid rounded mb-4" src="" alt="" id="article_main_image">
                            </div>

                            <div class="article_text"></div>

                            <div class="text-center mt-5 d-md-block d-lg-none">
                                <button class="btn btn-secondary" href="#" data-dismiss="modal">
                                    <i class="fas fa-times fa-fw"></i>
                                    закрити
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="pay_modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title font-weight-light text-muted"><i class="fa fa-laptop"></i> Послуги онлайн</h3>

                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            <div class="modal-body">
                <h5>Онлайн-рекомендації</h5>

                <ul class="list-group my-3">
                    <li class="list-group-item d-flex justify-content-between">
                        <span>Онлайн-рекомендації педіатра</span>
                        <span class="text-nowrap pl-3">
                            700 грн
                            <A href="https://secure.wayforpay.com/button/b8ce6fcfb45c8" class="btn btn-sm btn-success ml-1">придбати</A>
                        </span>
                    </li>

                    <li class="list-group-item d-flex justify-content-between">
                        <span>Онлайн-рекомендації дитячого невролога</span>
                        <span class="text-nowrap pl-3">
                            900 грн
                            <A href="https://secure.wayforpay.com/button/b102c10ac6830" class="btn btn-sm btn-success ml-1">придбати</A>
                        </span>
                    </li>

                    <li class="list-group-item d-flex justify-content-between">
                        <span>Онлайн-рекомендації з грудного вигодовування</span>
                        <span class="text-nowrap pl-3">
                            800 грн
                            <A href="https://secure.wayforpay.com/button/bb0d4bf755171" class="btn btn-sm btn-success ml-1">придбати</A>
                        </span>
                    </li>

                    <li class="list-group-item d-flex justify-content-between">
                        <span>Онлайн-рекомендації з дитячого сну</span>
                        <span class="text-nowrap pl-3">
                            980 грн
                            <A href="https://secure.wayforpay.com/button/ba56a7de2dc91" class="btn btn-sm btn-success ml-1">придбати</A>
                        </span>
                    </li>
                </ul>

                <h5>Супровід</h5>

                <ul class="list-group my-3">
                    <li class="list-group-item d-flex justify-content-between">
                        <span>
                            Онлайн-супровід протягом місяця

                            <br>

                            <span class="small">
                                передбачає формат "питання-відповідь" в листуванні в Телеграмі (текстом або голосовими повідомленнями)
                            </span>
                        </span>
                        <span class="text-nowrap pl-3">
                            3000 грн
                            <A href="https://secure.wayforpay.com/button/bfbf89432f01e" class="btn btn-sm btn-success ml-1">придбати</A>
                        </span>
                    </li>
                </ul>

                <h5>Вебінари</h5>

                <ul class="list-group my-3">
                    <li class="list-group-item d-flex justify-content-between">
                        <span>
                            Дитина народилася

                            <br>

                            <span class="small">
                                маніпуляції в пологовому, післяпологовий стан, жовтяниця, догляд за немовлям, сон, гігієна, грудне вигодовування, аптечка, огляди
                                <br>
                                <i class="far fa-clock"></i> 1 год 45 хв
                            </span>
                        </span>
                        <span class="text-nowrap pl-3">
                            600 грн
                            <A href="#" data-toggle="modal" data-dismiss="modal" data-target="#newborn_webinar_modal" class="btn btn-sm btn-success ml-1">придбати</A>
                        </span>
                    </li>

                    <li class="list-group-item d-flex justify-content-between">
                        <span>
                            Вебінар про прикорм

                            <br>

                            <span class="small" style="line-height:15px !important;">
                                коли і з чого починати, пюре чи шматочки, безпека та алергія, розмір порцій, напої, спеції, солодощі, апетит, харчові звички
                                <br>
                                <i class="far fa-clock"></i> 1 год 15 хв
                            </span>
                        </span>
                        <span class="text-nowrap pl-3">
                            490 грн
                            <A href="#" data-toggle="modal" data-dismiss="modal" data-target="#nutrition_webinar_modal" class="btn btn-sm btn-success ml-1">придбати</A>
                        </span>
                    </li>
                </ul>

                <p class="text-muted small">
                    Оплата здійснюється на рахунок ФОП платіжними картами Visa та MasterCard за допомогою сервісу WayForPay
                </p>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="pay_success_modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title font-weight-light text-muted">Дякуємо!</h3>

                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            <div class="modal-body">
                <div class="alert alert-success">
                    <p>
                        <i class="far fa-laugh-beam fa-lg mr-1"></i> <b>Оплата успішна!</b>
                    </p>
                    <p>
                        Ми зв'яжемося з Вами найближчим часом.
                    </p>
                    <p>
                        Якщо Ви придбали медіаматеріали (вебінари, відео тощо), вони будуть надіслані на вказану електронну адресу. Посилання на вебінар надсилається в день проведення заходу.
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="pay_fail_modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title font-weight-light text-muted">Нам шкода</h3>

                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            <div class="modal-body">
                <div class="alert alert-danger">
                    <i class="far fa-frown-open fa-lg mr-1"></i> Оплата неуспішна
                </div>

                <button class="btn btn-success btn-block" id="try_again">Спробуйте ще раз</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="nutrition_webinar_modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="my-0">Вебінар про прикорм</h4>

                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            <div class="modal-body">
                <p>
                    Теми, які розкриваються на вебінарі:
                </p>

                <div class="alert alert-info small">
                    <ul class="pl-0 my-0">
                        <li>У якому віці краще починати пропонувати дитині прикорм і як зрозуміти що дитина готова їсти іншу їжу, окрім грудного молока чи молочної суміші
                        <li>Який стільчик для годування обрати?
                        <li>Шматочки чи пюре? Переваги та недоліки різних видів прикорму
                        <li>Які продукти можна пропонувати? Яка порція має бути у різному віці?
                        <li>А якщо дитина вдавиться - що робити?
                        <li>А якщо буде алергія?
                        <li>Які можливі реакції? Як уникнути залізодефіцитної анемії? Що таке алергічний проктоколіт?
                        <li>Напої, спеції, солодощі - коли можна?
                        <li>Що таке чуйне годування?
                        <li>Як на початку прикорму не наробити помилок та сформувати здорову харчову поведінку, гарний апетит у дитини?
                    </ul>
                </div>

                <p>
                    <i class="fa fa-fw fa-laptop text-muted mr-1"></i> Запис вебінару буде відправлено на вашу пошту
                </p>

                <p>
                    <i class="far fa-fw fa-clock text-muted mr-1"></i> Тривалість вебінару – 1 година 15 хвилин
                </p>

                <p>
                    <i class="fa fa-fw fa-credit-card text-muted mr-1"></i> Запис можна придбати за 490 грн
                </p>

                <A href="https://secure.wayforpay.com/button/bcdd0830a34fc" class="btn btn-block btn-success">Придбати запис вебінару</A>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="newborn_webinar_modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="my-0">Вебінар "Дитина народилася"</h4>

                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            <div class="modal-body">
                <p>
                    Теми, які розкриваються на вебінарі:
                </p>

                <div class="alert alert-info small">
                    <ul class="pl-0 my-0">
                        <li>Як може виглядати дитина після народження? Що таке фізіологічні стани - де межа між нормою та патологією?
                        <li>Що таке жовтяниця новонароджених?
                        <li>Які маніпуляції в пологовому вам запропонують і чи варто їх робити?
                        <li>Післяпологовий блюз та післяпологова депресія - що це, як розпізнати та як подбати про свій емоційний стан?
                        <li>Що варто зробити для успішного старту грудного вигодовування?
                        <li>Дієта мами, яка годує грудьми - яка вона? І чи можна мамі приймати ліки, якщо раптом вона захворіє?
                        <li>Догляд: як піклуватися про шкіру, пупковий залишок, нігті та волосся?
                        <li>Коли та як купати?
                        <li>Яку дитячу косметику обрати?
                        <li>Які в нормі мають бути випорожнення малюка?
                        <li>Які особливості сну новонароджених?
                        <li>Чому дитина плаче? Як навчитися розпізнавати потреби малюка?
                        <li>Аптечка для новонароджених - які ліки потрібні?
                        <li>Які обстеження та огляди лікарів потрібні в перший рік життя?
                    </ul>
                </div>

                <p>
                    <i class="fa fa-fw fa-laptop text-muted mr-1"></i> Запис вебінару буде відправлено на вашу пошту
                </p>

                <p>
                    <i class="far fa-fw fa-clock text-muted mr-1"></i> Тривалість вебінару – 1 година 45 хвилин
                </p>

                <p>
                    <i class="fa fa-fw fa-credit-card text-muted mr-1"></i> Запис можна придбати за 600 грн
                </p>

                <A href="https://secure.wayforpay.com/button/b6fa52ce3c223" class="btn btn-block btn-success">Придбати запис вебінару</A>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="price_modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title font-weight-light text-muted"><i class="fa fa-notes-medical"></i> Послуги</h3>

                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            <div class="modal-body">
                <h5>Консультація</h5>

                <ul class="list-group my-3">
                    <?php foreach ($services as $service => $price) { ?>
                    <li class="list-group-item d-flex justify-content-between">
                        <span><?=$service ?></span>
                        <span class="text-nowrap pl-3"><?=$price ?> грн</span>
                    </li>
                    <?php } ?>
                </ul>

                <h5>Вакцинація</h5>

                <p class="small text-muted">
                    У вартість послуги входить огляд лікаря, послуга вакцинації.
                    <br>
                    Уточнюйте наявність вакцин перед записом.
                </p>

                <ul class="list-group mt-3">
                    <?php foreach ($vaccines as $vaccine) { ?>
                    <li class="list-group-item d-flex justify-content-between">
                        <span><?=$vaccine->getName() ?></span>
                        <span class="text-nowrap"><?=$vaccine->getPrice() ?> грн</span>
                    </li>
                    <?php } ?>
                </ul>
            </div>
        </div>
    </div>
</div>

<script>
    let close_dates=<?=json_encode($close_dates) ?>;
</script>