<div class="row justify-content-sm-center">
    <div class="col-sm-auto">
        <form id="login_form">
            <input type="hidden" name="g-recaptcha-response">

            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text" style="width:40px;"><i class="fa fa-user" aria-hidden="true"></i></span>
                </div>
                <input type="text" class="form-control" name="username" style="border-top-left-radius:0 !important; border-bottom-left-radius:0 !important;">
            </div>

            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text" style="width:40px;"><i class="fa fa-key" aria-hidden="true"></i></span>
                </div>
                <input type="password" class="form-control" name="password" style="border-top-left-radius:0 !important; border-bottom-left-radius:0 !important;">
            </div>

            <div class="row h-100">
                <div class="col px-1"></div>

                <div class="col-auto text-center px-2">
                    <button class="btn btn-success">Увійти <i class="fa fa-sign-in-alt ml-1"></i></button>
                </div>

                <div class="col px-1 py-0 my-auto">
                    <div class="my-auto">
                        <i class="fa fa-lg fa-spin fa-spinner text-muted" style="display:none;"></i>
                        <i class="fa fa-lg fa-check text-success" style="display:none;"></i>
                        <i class="fa fa-lg fa-times text-danger" style="display:none;"></i>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>