<table class="table table-striped" id="vaccines_grid">
    <thead>
        <tr>
            <th>Вакцина</th>
            <th>Тип</th>
            <th>Країна</th>
            <th>Міс</th>
            <th>Ціна</th>
            <th>
                <span class="d-none d-md-inline">tabletki.ua</span>
                <span class="d-inline d-md-none"><i class="fa fa-external-link-alt"></i></span>
            </th>
            <th>Аналог</th>
            <th>Обов'язкова</th>
            <th>Коментар</th>
        </tr>
    </thead>
</table>

<script src="/js/vaccines.js?nocache=<?=filemtime(APPLICATION_TOP_PATH.'/public/js/vaccines.js') ?>" defer></script>