<?php

/** @var $layout array */
/** @var $config array */

?>

<!DOCTYPE html>
<html lang="uk">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Кабінет дитячого лікаря ДітиКвіти, м. Чернівці</title>

    <link href="/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker3.standalone.min.css" integrity="sha512-p4vIrJ1mDmOVghNMM4YsWxm0ELMJ/T0IkdEvrkNHIcgFsSzDi/fV7YxzTzb3mnMvFPawuIyIrHcpxClauEfpQg==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link href="/css/bootstrap.min.css" rel="stylesheet">
    <link href="/css/custom.css?nocache=<?=filemtime(APPLICATION_TOP_PATH.'/public/css/custom.css') ?>" rel="stylesheet">

    <link rel="shortcut icon" href="/img/favicon.ico" type="image/x-icon">
    <link rel="icon" href="/img//favicon.ico" type="image/x-icon">

    <meta property="og:title" content="Кабінет дитячого лікаря ДітиКвіти, м. Чернівці" />
    <meta property="og:description" content="<?=$config['address'] ?>" />
    <meta property="og:image" content="/img/logo.png" />
</head>

<body id="page-top" style="padding-top:100px;">

<nav class="bg-white text-uppercase border-bottom fixed-top pt-2" style="height:100px;">
    <div class="container px-1">
        <div class="form-row">
            <div class="col-auto">
                <IMG src="img/logo.svg" height="80" class="mx-1 mt-0 mt-lg-1">
            </div>

            <div class="col">
                <div class="form-row">
                    <div class="col-12 col-lg-auto pt-0 pt-lg-3">
                        <A class="navbar-brand mr-0 js-scroll-trigger text-decoration-none py-0 py-lg-1" href="#page-top">
                            <span class="text-success">Кабінет</span>
                            <span class="text-warning">дитячого</span>
                            <span class="text-info">лікаря</span>

                            <div style="font-size:60%;" class="text-muted">
                                <b>м. Чернівці, <nobr><?=$config['address'] ?></nobr></b>
                            </div>
                        </A>
                    </div>

                    <div class="col-12 col-lg-auto ml-auto pt-1 pt-lg-4" id="top_menu">
                        <A class="py-1 py-lg-2 px-2 px-lg-3 js-scroll-trigger btn btn-outline-secondary mr-1 d-none d-sm-inline-block" href="#how_to_find">
                            <i class="fa fa-phone-alt"></i>
                            Контакти
                        </A>

                        <A class="py-1 py-lg-2 px-2 px-lg-3 js-scroll-trigger btn btn-outline-secondary mr-1" href="#reviews">
                            <i class="fa fa-comments"></i>
                            Відгуки
                        </A>

                        <A class="py-1 py-lg-2 px-2 px-lg-3 js-scroll-trigger btn btn-outline-secondary mr-1" href="#articles">
                            <i class="fa fa-list"></i>
                            Статті
                        </A>

                        <A class="py-1 py-lg-2 px-2 px-lg-3 btn btn-success text-white mr-3 d-none d-lg-inline-block" data-toggle="modal" data-target="#appointment_modal">
                            <i class="fa fa-pen"></i>
                            Запис <span class="d-none d-xl-inline">на прийом</span>
                        </A>

                        <A class="btn btn-outline-secondary rounded-circle d-inline-flex justify-content-center align-items-center" title="Instagram" href="https://www.instagram.com/dr_svitlana/" style="width:2.5em; aspect-ratio:1/1;">
                            <i class="fab fa-fw fa-instagram" style="font-size:150%;"></i>
                        </A>
                    </div>
                </div>
            </div>
        </div>
    </div>
</nav>

<?=$layout['body'] ?>

<section class="py-3 text-center alert alert-secondary mb-0 mt-4 rounded-0 small" style="text-wrap:balance;">
    <div class="container px-0">
        Ліцензія видана наказом Міністерства охорони здоров'я України&nbsp;<u><A target="_blank" title="Витяг відомостей з Ліцензійного реєстру МОЗ з медичної практики" class="text-dark" href="/Витяг відомостей з Ліцензійного реєстру МОЗ з медичної практики.pdf">№1949&nbsp;(від 21.08.2020)</A></u>. ЄДРПОУ&nbsp;3371807241
    </div>
</section>

<form name="sentMessage" id="contactForm" novalidate="novalidate">
    <div class="modal" id="appointment_modal" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h3 class="modal-title font-weight-light text-muted"><i class="fas fa-notes-medical"></i> Запис на прийом</h3>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="control-group">
                        <div class="form-group">
                            <label class="mb-0" for="name">Ім'я та прізвище дитини</label>
                            <input class="form-control" id="name" type="text" required="required" data-validation-required-message="Будь ласка введіть ім'я та прізвище дитини">
                            <p class="help-block text-danger small"></p>
                        </div>
                    </div>

                    <div class="control-group">
                        <div class="form-group">
                            <label class="mb-0" for="phone">Вік дитини</label>
                            <input class="form-control" id="age" type="text">
                        </div>
                    </div>

                    <div class="control-group">
                        <div class="form-group">
                            <label class="mb-0" for="phone">Контактний телефон</label>
                            <input class="form-control" id="phone" type="tel" required="required" data-validation-required-message="Будь ласка введіть телефон">
                            <p class="help-block text-danger small"></p>
                        </div>
                    </div>

                    <div class="control-group">
                        <div class="form-group">
                            <label class="mb-0" for="message">Коротко опишіть причину звернення</label>
                            <textarea class="form-control" id="message" rows="4" required="required" data-validation-required-message="Будь ласка опишіть причину звернення"></textarea>
                            <p class="help-block text-danger small"></p>
                        </div>
                    </div>

                    <div class="control-group">
                        <div class="form-group mb-0">
                            <label class="mb-0" for="date">Оберіть бажану дату</label>
                            <input class="form-control bg-white" type="text" autocomplete="off" readonly id="date" data-date-start-date="<?=date('G')>16 ? date('d.m.Y', strtotime('tomorrow')) : date('d.m.Y') ?>" data-date-end-date="<?=date('d.m.Y', strtotime('last day of next month')) ?>">
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <i class="fa fa-spinner fa-spin text-muted fa-lg d-none"></i>

                    <button type="submit" class="btn btn-primary btn-xl" id="sendMessageButton">Відправити</button>
                </div>
            </div>
        </div>
    </div>
</form>

<div class="modal" id="contact_success_modal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title font-weight-light text-muted"><i class="fa fa-clipboard-check"></i> Запит отримано</h3>
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="alert alert-success my-0 py-2 text-center">
                    Ваш запит отримано
                    <br>
                    Ми зв'яжемося з вами <?=(date('N')<6 && date('G')>=11 && date('G')<18) ? 'найближчим часом' : 'в робочий час (ПН-ПТ з 11 до 18)' ?>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрити</button>
            </div>
        </div>
    </div>
</div>

<A data-toggle="modal" data-target="#appointment_modal" class="d-lg-none text-white btn-success position-fixed p-2 font-weight-light rounded-top text-decoration-none" style="z-index:99; right:0; top:50%; transform:rotate(-90deg) translateX(50%) translateY(-50%); transform-origin:right;" href="#"><b>Записатись на прийом</b></A>

<script src="/vendor/jquery/jquery.min.js"></script>
<script src="/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="/vendor/jquery-easing/jquery.easing.min.js"></script>
<script src="/js/jqBootstrapValidation.js"></script>
<script src="/js/freelancer.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/locales/bootstrap-datepicker.uk.min.js" integrity="sha512-zj4XeRYWp+L81MSZ3vFuy6onVEgypIi1Ntv1YAA6ThjX4fRhEtW7x+ppVnbugFttWDFe/9qBVdeWRdv9betzqQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<script src="/js/articles.js?nocache=<?=filemtime(APPLICATION_TOP_PATH.'/public/js/articles.js') ?>"></script>
<script src="/js/contact_me.js?nocache=<?=filemtime(APPLICATION_TOP_PATH.'/public/js/contact_me.js') ?>"></script>
<script src="/js/quick_search.js"></script>

</body>
</html>